### ISSUE TITLE
Check ErrorInformation alignment with Android codebase

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-swift#101]
See [here](https://github.com/ably/ably-asset-tracking-android/blob/fb34d99045dac423134ba0826fbaaad560058852/core-sdk/src/main/java/com/ably/tracking/ListenerInterfaces.kt#L19).

Prompted by: https://github.com/ably/ably-asset-tracking-cocoa/pull/81.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-725) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
@ben-xD I think that it was based on Ably's `ErrorInfo` class and that's why there are all those fields :thinking: I don't have enough knowledge about Ably to decide if it should stay like this or not :wink:
