### ISSUE TITLE
Better approach for Objective-C facade

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-swift#102]
The additional `delegateObjectiveC` property on publisher instances is ugly / awkward, and it pollutes the Swift namespace.

We need to work out a better approach. This could involve avoiding the `Result` type, [as Ricardo prefers](https://github.com/ably/ably-asset-tracking-cocoa/pull/85#discussion_r578496865), or it might involve going down the route of something similar to what we did in the Android codebase of having [an explicit facade API surface](https://github.com/ably/ably-asset-tracking-android/blob/fb34d99045dac423134ba0826fbaaad560058852/publishing-sdk-java/src/main/java/com/ably/tracking/publisher/java/PublisherFacade.kt#L14).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-726) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Perhaps need to audit our use of `@objc` at the same point also (thunks).

**Comment by lukasz-szyszkowski** [comment]
Since we decided that AAT will not support Objective-C, this issue can be closed.
More here https://github.com/ably/ably-asset-tracking-swift/issues/218
