### ISSUE TITLE
Unify wrappers for the Ably SDK

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#107]
iOS has separate wrappers for Ably for Subscriber and Publisher which leads to code duplication. They should be unified and moved to a shared/common module.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-730) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
as an expansion of the wrapper, we should take into account this issue https://github.com/ably/ably-asset-tracking-android/issues/608

**Comment by maratal** [comment]
@lukasz-szyszkowski  https://github.com/ably/ably-asset-tracking-android/issues/608#issuecomment-1036455674
