### ISSUE TITLE
Codesigning in GitHub workflows

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-swift#11]
Related: https://github.com/ably/ably-asset-tracking-cocoa/pull/6#discussion_r536180195

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-731) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
This issue refers to `fastlane` and `cocoapods` which aren't available in the current state of the SDK. I'm assuming that we can close it. @QuintinWillison
