### ISSUE TITLE
Modify Publisher example app to work in background

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#110]
The iOS example app isn't using the publisher in the background like the Android app does. Maybe it would be a good idea to try and implement something similar for the iOS example app because while I was implementing it on Android a few additional API requirements showed up and changed our final API so it's more developer-friendly.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-732) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
This issue is "on hold" until https://github.com/ably/ably-asset-tracking-swift/pull/219 and https://github.com/ably/ably-asset-tracking-swift/pull/220 is merged
