### ISSUE TITLE
Handle resolutions for the location engine in the Publisher

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#113]
On iOS, there's no way to tell the location engine which resolution should it use. So only resolutions for sending location updates through Ably are working. On Android, we've had to write whole location engines implementations to allow resolution changing. Do we want to implement it on iOS too?

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-738) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
@KacperKluka would you elaborate on this?

**Comment by KacperKluka** [comment]
So we want to be able to change the location engine resolution when it's running. For example, this can be used to limit the GPS sensor usage when there are no subscribers on the channel. 

With the default Mapbox implementation that's not possible as we can only provide the location engine resolution during its creation. Therefore, we've created [our own subclass](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-sdk/src/main/java/com/ably/tracking/publisher/locationengine/ResolutionLocationEngine.kt) of the `LocationEngine` which allows changing the resolution during runtime. Then we've taken Mapbox engines code and adjusted it for the location engine subclass ([example](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-sdk/src/main/java/com/ably/tracking/publisher/locationengine/GoogleLocationEngine.kt)). Finally, we [create](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-sdk/src/main/java/com/ably/tracking/publisher/Mapbox.kt#L376) and [use](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-sdk/src/main/java/com/ably/tracking/publisher/Mapbox.kt#L183) one of our own location engines when creating the Mapbox instance.
This allows us to simply [call one method](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-sdk/src/main/java/com/ably/tracking/publisher/Mapbox.kt#L365) and change the resolution whenever we want to :wink:
