### ISSUE TITLE
Handle errors when starting Subscriber and Publisher

### ISSUE THREAD

**Issue by robertkuraj** [ably/ably-asset-tracking-swift#121]
We aren't handling errors when the Publisher or Subscriber is started. 
For example, starting up the Ably SDK can throw an error that will crash our SDKs. For now there is force try used in the ecample apps.
This is the iOS version of the ably/ably-asset-tracking-common#10

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-740) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
I'm not sure if handling `ARTRealtime` exceptions are even possible with the current codebase. That's because `ARTRealtime` doesn't throw any exception on init. I know it's done in Android. They could do this because they manage to throw exceptions in the `AblyRealtime` initialiser cascade ([HERE](https://github.com/ably/ably-asset-tracking-android/pull/249/files#diff-baf8644244d013d061c0a0d0bc74b8f8156783cc77f7796198b11172cccb9d38R149) and [HERE](https://github.com/ably/ably-asset-tracking-android/pull/249/files#diff-baf8644244d013d061c0a0d0bc74b8f8156783cc77f7796198b11172cccb9d38R149))
To be honest, I have no idea how to solve it in AAT Swift (if it's even possible). 
WDYT @lawrence-forooghian @ben-xD @maratal @QuintinWillison?

**Comment by maratal** [comment]
Isn't it closed in https://github.com/ably/ably-asset-tracking-swift/pull/132 ?

**Comment by lukasz-szyszkowski** [comment]
> Isn't it closed in #132 ?

I'm not sure, there is only `presence` failure managed:
```swift
func start(completion: @escaping ResultHandler<Void>) {
        // Trigger offline event at start
        delegate?.subscriberService(sender: self, didChangeChannelConnectionStatus: .offline)
        channel.presence.subscribe({ [weak self] message in
            logger.debug("Received presence update from channel", source: "AblySubscriberService")
            self?.handleIncomingPresenceMessage(message)
        })

        // Force cast intentional here. It's a fatal error if we are unable to create presenceData JSON
        let data = try! presenceData.toJSONString()

        channel.presence.enter(data) { error in
            guard let error = error else {
                logger.debug("Entered to channel presence successfully", source: "AblySubscriberService")
                completion(.success)
                return
            }
            
            logger.error("Error during joining to channel presence: \(String(describing: error))", source: "AblySubscriberService")
            completion(.failure(error.toErrorInformation()))
        }

        channel.subscribe(EventName.raw.rawValue) { [weak self] message in
            logger.debug("Received raw location message from channel", source: "AblySubscriberService")
            self?.handleLocationUpdateResponse(forEvent: .raw, messageData: message.data)
        }

        channel.subscribe(EventName.enhanced.rawValue) { [weak self] message in
            logger.debug("Received enhanced location message from channel", source: "AblySubscriberService")
            self?.handleLocationUpdateResponse(forEvent: .enhanced, messageData: message.data)
        }
    }
```

**Comment by lukasz-szyszkowski** [comment]
Ok, I've finished code reviewing and in my opinion, the Ably SDK failures are managed and forwarded to AAT Swift. Below I pointed out the places in code where they are managed.

## Publisher

https://github.com/ably/ably-asset-tracking-swift/blob/0885a04f729964d3b396a0f5e735b7ae128b2ef6/Sources/AblyAssetTrackingPublisher/Services/DefaultAblyPublisherService.swift#L63-L69

https://github.com/ably/ably-asset-tracking-swift/blob/0885a04f729964d3b396a0f5e735b7ae128b2ef6/Sources/AblyAssetTrackingPublisher/Services/DefaultAblyPublisherService.swift#L97-L103

https://github.com/ably/ably-asset-tracking-swift/blob/0885a04f729964d3b396a0f5e735b7ae128b2ef6/Sources/AblyAssetTrackingPublisher/Services/DefaultAblyPublisherService.swift#L131-L137

https://github.com/ably/ably-asset-tracking-swift/blob/0885a04f729964d3b396a0f5e735b7ae128b2ef6/Sources/AblyAssetTrackingPublisher/Services/DefaultAblyPublisherService.swift#L182-L188

## Subscriber

https://github.com/ably/ably-asset-tracking-swift/blob/0885a04f729964d3b396a0f5e735b7ae128b2ef6/Sources/AblyAssetTrackingSubscriber/Services/DefaultAblySubscriberService.swift#L49-L55

https://github.com/ably/ably-asset-tracking-swift/blob/0885a04f729964d3b396a0f5e735b7ae128b2ef6/Sources/AblyAssetTrackingSubscriber/Services/DefaultAblySubscriberService.swift#L77-L83

https://github.com/ably/ably-asset-tracking-swift/blob/0885a04f729964d3b396a0f5e735b7ae128b2ef6/Sources/AblyAssetTrackingSubscriber/Services/DefaultAblySubscriberService.swift#L160-L166

**Comment by maratal** [comment]
So this issue needs some clarification then IMHO.

**Comment by QuintinWillison** [comment]
If you're happy that this has been covered already then we can close this issue. 😁
