### ISSUE TITLE
Use different approach of passing class name for debugger instead of using literal string.

### ISSUE THREAD

**Issue by robertkuraj** [ably/ably-asset-tracking-swift#127]
Discussed here:
https://github.com/ably/ably-asset-tracking-cocoa/pull/124#discussion_r601766844

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-741) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
I've changed it to
```swift
String(describing: Self.self)
```
which is more universal way than a static string
