### ISSUE TITLE
Release to Swift Package Manager (SPM)

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-asset-tracking-swift#148]
Blocked by:

- https://github.com/ably/ably-asset-tracking-cocoa/issues/106 - MapBox dependency update
- https://github.com/ably/ably-cocoa/issues/819 - ably-cocoa dependency update

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-893) by [Unito](https://www.unito.io)

**Comment by ben-xD** [comment]
We have added SPM support, but we have not _released_ it yet.

**Comment by ben-xD** [comment]
For release:
- We should use an SPM release of `ably-cocoa` in the `Package.swift` file. (not yet available, awaiting https://github.com/ably/ably-cocoa/pull/1136)
- Create a git tag for a version for SPM can find it, and potentially update the README with this new version.
