### ISSUE TITLE
Renaming to `ably-asset-tracking-swift`

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-asset-tracking-swift#151]
We could rename this library to `ably-asset-tracking-swift`

## Benefits
- People search for **swift** library more than they search for Cocoa. See github repo lists like [awesome-swift](https://github.com/Wolg/awesome-swift) which has 5.4k stars, and [awesome-cocoa](https://github.com/v-braun/awesome-cocoa) has 46 stars.
- the SDK is written in Swift
- Standard naming convention for lots of swift libraries

## Potential concerns:
- Naming it swift might push away Objective-C developers. However, they're used to using Swift libraries in their project, and this is quite easy: https://stackoverflow.com/questions/37503201/using-swift-library-in-an-objective-c-project.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-898) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Relates to https://github.com/ably/ably-asset-tracking-cocoa/issues/148.

**Comment by ben-xD** [comment]
It looks like no one was resistant to this change when I mentioned it in the stand up. I think we should rename it, WDYT @QuintinWillison ? I don't have the Github permissions to do it though.

**Comment by QuintinWillison** [comment]
I'm going to mention this in Slack now to give people one last opportunity to object.

**Comment by kavalerov** [comment]
I don't mind doing this, especially since we are early in the lifecycle of this SDK.
