### ISSUE TITLE
Create Swift Package Collection to conveniently store all Ably SDKs in one group

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-asset-tracking-swift#159]
Xcode 13 introduces [Swift Package Collections](https://swift.org/blog/package-collections), where you can group together a bunch of packages neatly. This is an example of the Apple Swift Package Collection: 

![Screenshot 2021-06-14 at 08 49 57](https://user-images.githubusercontent.com/24711048/121857538-a3a8db80-cced-11eb-9371-4b7230fa72a4.png)

It would be great to have Ably Cocoa, Ably Asset Tracking Publisher, and Subscriber listed together in this package.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-933) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
The SwiftPM Collection is really cool but unfortunately, I don't see the reason to use it in Ably projects.
AAT Swift libs are dependent on `ably-cocoa`(which is downloaded automatically)  so we should avoid giving the user the option to install `ably-cocoa` manually - I can't find a reason to do this.
For everyone who is interested in how it works, here is the WWDC Video https://developer.apple.com/videos/play/wwdc2021/10197/

@AndyNicks @jamienewcomb In my opinion, we can close this issue.

**Comment by AndyNicks** [comment]
Agree
