### ISSUE TITLE
Supporting location button (in SDK and Example apps)

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-asset-tracking-swift#160]
## Background

iOS 15 has added `CoreLocationUI` framework (this is only available on iOS15+), which includes `LocationButton` and `CLLocationButton`. These were designed for UI/ UX improvement. Users often press a "start navigation" button already, and these buttons will give one-time location permission when it pressed automatically, rather than pop-up another permissions alert asking for one-time location permission. This means users are less encouraged to give location permission to an app **forever** when they get tired of the permissions alert.

WWDC 21 video: https://developer.apple.com/videos/play/wwdc2021/10102/
Documentation: https://developer.apple.com/documentation/corelocationui/locationbutton

## Tasks

- We could add `#available(iOS 15, *)` logic in the example apps to show a LocationButton instead of asking the user for one-time location permission, or "while app is in use" (forever) permission. This is the most privacy preserving option.
- We could ensure support for `LocationButton` implementation by SDK users/ customers

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-932) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
I've watched the WWDC video and IMO we don't need this in the example App furthermore we won't implement it to the SDK because it's related to UI and location service that is generic in AAT Swift.

**Comment by lukasz-szyszkowski** [comment]
I'm closing this issue
cc: @jamienewcomb @AndyNicks
