### ISSUE TITLE
Add Swift Package to Swift Package Index

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-asset-tracking-swift#167]
Add this GitHub repo URL to https://swiftpackageindex.com/add-a-package so users can find it more easily.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-956) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
Waiting for https://github.com/SwiftPackageIndex/PackageList/ to be forked into the Ably organisation 
person in charge: @QuintinWillison

**Comment by ben-xD** [comment]
Hey @lukasz-szyszkowski, in ably-cocoa @maratal did this using his own Github fork: https://github.com/SwiftPackageIndex/PackageList/pull/1289

Anyone can create PRs for adding repos to SPI

**Comment by lukasz-szyszkowski** [comment]
> 

Thanks :) but I think using the official GH team looks better ;) anyway if creating this PR by the `ably` team is problematic I can of course fork it by myself. cc: @QuintinWillison

**Comment by lukasz-szyszkowski** [comment]
https://swiftpackageindex.com/ably/ably-asset-tracking-swift done.
