### ISSUE TITLE
Share build outputs instead of building the library 3 times in separate workflows

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-asset-tracking-swift#168]
All 3 workflows, assemble, check and docs require downloading dependencies and building the libraries. This is because assembling `.framework`s, running tests and building docs all rely on `xcodebuild`. Because they all need the same build output, they should ideally share them instead of re-creating them in 3 separate workflows. We could do this by sharing files between workflows, or by moving all workflows into one and just running them serially.

PS: This would reduce the cost of CI by approximately **3x**. Probably from $0 to $0. The main benefit of doing this is resource usage: sometimes a workflow is stuck without doing any real work (it might be waiting for free capacity).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-960) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
WDYT? @QuintinWillison @lawrence-forooghian @maratal

**Comment by lawrence-forooghian** [comment]
Whether it'd cause errors or not, I don't know.

Before investing time to share files between workflows, we could test it out by trying to combine all of the workflow files into a single workflow, and seeing if that reduces the execution time of the individual steps or not.

We haven't implemented anything like this on ably/ably-cocoa – we've been happy until now to duplicate work between jobs.

**Comment by QuintinWillison** [comment]
I've only just seen this issue. It's noise and counter to the direction I'm taking the SDK Team in, as a whole, in respect of our use of GitHub workflows.
