### ISSUE TITLE
Route is not recalculated when user is off route

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-asset-tracking-swift#184]
It would be good to recalculate the route when user is off-route, as per the [Mapbox rerouting documentation](https://docs.mapbox.com/ios/beta/navigation/guides/rerouting/). Currently, `locationManager.requestLocation()` is called once, so `handleLocationUpdate` is only called once, which so the following directions calculation is done only once (when `TrackableReadyToTrackEvent` is fired), at the start:

```swift
        directions.calculate(options) { [weak self] (_, result) in
            guard let self = self else { return }
            switch result {
            case .failure(let error):
                self.handleErrorCallback(error: ErrorInformation(error: error))
            case .success(let response):
                guard let route = response.routes?.first else {
                    let errorInformation = ErrorInformation(type: .publisherError(errorMessage: "Missing route in Directions response."))
                    self.handleErrorCallback(error: errorInformation)
                    return
                }
                self.handleRouteCallback(route: route)
            }
        }
```

@lukasz-szyszkowski has said:

I confirm, it’s calculated on `TrackableReadyToTrackEvent` which is fired by `TrackTrackableEvent` and initially it’s called by this method:
```
func track(trackable: Trackable, completion: @escaping ResultHandler<Void>) {
    let event = TrackTrackableEvent(trackable: trackable,
                                    resultHandler: completion)
    enqueue(event: event)
}
```

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1180) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
I talked to @KacperKluka about AAT Android, and we agree the route recalculating mechanism should be resolved on the map provider SDK, in our case this is the Mapbox. In view of this, I'm closing this issue. 

cc: @jamienewcomb @AndyNicks
