### ISSUE TITLE
Add `swiftlint` as a `pre-commit hook`

### ISSUE THREAD

**Issue by lukasz-szyszkowski** [ably/ably-asset-tracking-swift#210]
According to code quality, we have to add a linter to the project.
Since the project is configured as a `Swift Package Manager` there is no `build step` like in the regular Xcode project, so the idea is to create a `pre-commit hook` for `swiftlint`.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1374) by [Unito](https://www.unito.io)

**Comment by ben-xD** [comment]
I also need one to run `flutter format .`, it's been too annoying to fail CI because the code is not formatted. 😅

**Comment by lukasz-szyszkowski** [comment]
> I also need one to run `flutter format .` in Ably Flutter, it's been too annoying to fail CI because the code is not formatted. 😅
you need to run `flutter format` on `aat swift lib`  ?

**Comment by ben-xD** [comment]
No, I meant for Ably Flutter, not for AAT.

**Comment by ben-xD** [comment]
I've added a local one for me to format files. My `.git/hooks/pre-commit` file looks like:
```
#!/bin/sh

/opt/flutter/bin/flutter format --set-exit-if-changed .
```

It's quite simply really, I wish I did it sooner :)

**Comment by lukasz-szyszkowski** [comment]
It's currently unavailable to do this task properly, I mean using a swift command line like `swift run swiftlint` 
The `Mapbox` has inconsistency with the versioning of their products. More here https://github.com/mapbox/mapbox-maps-ios/issues/966

**Comment by ben-xD** [comment]
Support for pre-commit was added in a recent SwiftLint PR: https://github.com/realm/SwiftLint/pull/3714

**Comment by lukasz-szyszkowski** [comment]
> Support for pre-commit was added in a recent SwiftLint PR: https://github.com/realm/SwiftLint/pull/3714.
> 
> 
> 
> After reading further, by "pre-commit", the issue is talking about [pre-commit framework](https://pre-commit.com/), which is not the same as git pre-commit hook.
> 
> 
> 
> I used Swiftformat in my precommit in Ably Flutter, take a look at https://github.com/ably/ably-flutter/pull/267/files

Yea, but I want to use SPM, `swift run swiftlint`. If it’ll be possible (check my comment about Mapbox versions) I’ll check how to use it in pre-commit

**Comment by jamienewcomb** [comment]
Closing as we have decided we will not do this
