### ISSUE TITLE
We need to check how Swift-idiomatic the library is

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-asset-tracking-swift#217]
I've only looked at the AAT library very briefly so far, so consider these opinions possibly hastily-formed. But I notice that there are decisions (like using classes instead of structs for things that are clearly value types, like `Resolution` etc) that seem to have been made either:

1. because they were copied directly from the Kotlin API, or:
2. because we wanted to make a public API that's compatible with both Swift and Objective-C.

If it's just 1., then we should change these things (@QuintinWillison [has indicated (Ably Slack)](https://ably-real-time.slack.com/archives/C01EPJENRD0/p1638538463161300?thread_ts=1638538377.160700&cid=C01EPJENRD0) that we should be aiming for an API idiomatic to Swift).

If it's 2, then we should consider:

- whether we _need_ Objective-C compatibility at this point ([my question in Ably Slack](https://ably-real-time.slack.com/archives/C01EPJENRD0/p1638539164164400))
- and if we do need it, then whether we'd prefer to make a separate Objective-C interface instead of compromising the Swift one ([@QuintinWillison has indicated that he'd prefer not to compromise the Swift interface, and I pointed out how writing an Objective-C facade could be more involved than the Java equivalent (Ably Slack)](https://ably-real-time.slack.com/archives/C01EPJENRD0/p1638538684163200?thread_ts=1638538377.160700&cid=C01EPJENRD0))

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1408) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
This also relates to #216, where we're potentially compromising the Swift interface in order to remove specialised code for Objective-C.

**Comment by lawrence-forooghian** [comment]
Update: [@QuintinWillison has decided (Ably Slack)](https://ably-real-time.slack.com/archives/C01EPJENRD0/p1638541596167700?thread_ts=1638539164.164400&cid=C01EPJENRD0) that this library does not need to be compatible with Objective-C.

**Comment by QuintinWillison** [comment]
Indeed. Also agreed by @AndyNicks. We should probably complete #218 before tackling this issue.

**Comment by lukasz-szyszkowski** [comment]
This task has to be marked as pending since this https://github.com/ably/ably-asset-tracking-swift/pull/219 and this https://github.com/ably/ably-asset-tracking-swift/pull/220 isn't merged
