### ISSUE TITLE
Add raw locations to the Subscriber SDK

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-asset-tracking-swift#251]
enable listening for raw locations in the Subscriber SDK see https://github.com/ably/ably-asset-tracking-android/pull/495

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1532) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
@AndyNicks this linked PR https://github.com/ably/ably-asset-tracking-android/pull/495 has nothing to an example app as the github label might suggest - or am I wrong? :)

**Comment by AndyNicks** [comment]
No you are right. Thanks for spottuing it.
