### ISSUE TITLE
Send resolution to subscriber

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-asset-tracking-swift#253]
The currently active resolution information should be sent as separate messages on the channel created for a trackable. It should serve as a debug feature that by default is disabled. see https://github.com/ably/ably-asset-tracking-android/issues/509 for details

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1535) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
The above solution is outdated, so my implementation needs some changes.
More here https://github.com/ably/ably-asset-tracking-android/issues/638
cc: @AndyNicks
