### ISSUE TITLE
Check: Zooming does not improve resolution: Resolution-type events does not get sent

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-asset-tracking-swift#255]
Please check if the zooming improves resolution (see https://github.com/ably/ably-asset-tracking-android/issues/535 for details)

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1538) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
This problem also exists in AATSwift.
