### ISSUE TITLE
Disable predictions in the Mapbox SDK

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-asset-tracking-swift#256]
We should allow the users to disable the predictions of Mapbox SDK. Since this can only be set during MapboxNavigation creation we should add a new field in the MapConfiguration object for enabling and disabling predictions. By default, this should be set to true to ensure backwards compatibility.

To disable the predictions we have to set navigatorPredictionMillis to 0.

See https://github.com/ably/ably-asset-tracking-android/pull/547 for additional details

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1537) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
The requirements here have changed; now predictions should just be permanently turned off.

We're waiting for a new release of the iOS Mapbox SDK that allows this; we're assuming it will just be a one-line change to our initialization of Mapbox.

**Comment by ikbalkaya** [comment]
Blocked by https://github.com/mapbox-collab/Ably-DH-Collab/issues/1
