### ISSUE TITLE
Run SwiftLint in CI

### ISSUE THREAD

**Issue by jamienewcomb** [ably/ably-asset-tracking-swift#258]

**Comment by QuintinWillison** [comment]
Replacement for #210.

We will not be including any kind of opinionated requirements, based on Git hooks, on developers who wish to maintain this codebase.

It is up to developers whether, and how, they choose to run lint tools locally. They may choose, themselves, to configure their local Git tool to use a Git hook but we will not foist this on them. We _must_ run these tools in the CI environment, and I support developers who wish to simply push up to a feature branch and allow CI to run checks for them. It can be noisier that way, but everybody has their own workflows / ways of working, plus differing contexts.

**Comment by lukasz-szyszkowski** [comment]
Firstly I'll fix all of [these](https://github.com/ably/ably-asset-tracking-swift/files/8771252/SwiftLint.Report.pdf) warnings (and one error), and then I'll add the `swiftlint` step into the CI

**Comment by deanna-lad** [comment]
The corresponding Jira issue is https://ably.atlassian.net/browse/SDK-1554
