### ISSUE TITLE
Move appropriate location rendering functional from example app to the SDK

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-asset-tracking-swift#262]
We need to move as much rendering functional from Subscriber app to the SDK because customers want to have a subscriber app as simple as possible and focus mostly on UI rather than location visualisation

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1613) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
blocked by #263

**Comment by KacperKluka** [comment]
Closing because [the corresponding PR](https://github.com/ably/ably-asset-tracking-swift/pull/293) was landed.
