### ISSUE TITLE
Add constant location engine resolution to the publisher example app

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-asset-tracking-swift#264]
We should allow specifying the constant location engine resolution in the publisher example app. It should be added to the settings screen. We will need to add:

-     a checkbox for enabling/disabling the constant location engine resolution,
-     input fields for specifying the constant resolution.

see https://github.com/ably/ably-asset-tracking-android/pull/636

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1617) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
It's blocked by https://github.com/ably/ably-asset-tracking-swift/issues/276
