### ISSUE TITLE
Replay location data recorded in the common format

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#290]
We have created a common GeoJSON based format of trip history recordings to be able to replay Android recordings on iOS and vice versa. The JSON schema of locations format can be found [here](https://github.com/ably/ably-asset-tracking-common/blob/main/test-resources/geo/location-schema.json). This is implemented in Android via [LocationHistoryData](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-sdk/src/main/java/com/ably/tracking/publisher/LocationHistoryModels.kt#L14) and [GeoJsonMessage](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-sdk/src/main/java/com/ably/tracking/publisher/GeoJsonModels.kt#L8) classes.

The iOS publisher should be able to accept location history data in the common format so they can be replayed (currently it seems that [it only accepts locations in the CLLocation format](https://github.com/ably/ably-asset-tracking-swift/blob/bd26232c269a68ec460f5629d25c1e1783b53e5b/Sources/AblyAssetTrackingPublisher/LocationSource.swift#L12)).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1751) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
As part of this work, we should formally document the `LocationHistoryData` type by adding a schema for it. See https://github.com/ably/ably-asset-tracking-common/issues/62.

**Comment by arturjaworski** [comment]
I've moved documentation work to #437
