### ISSUE TITLE
Verify if `LocationSource` is used in Publisher

### ISSUE THREAD

**Issue by lukasz-szyszkowski** [ably/ably-asset-tracking-swift#301]
I think the `LocationSource` is unused in `DefaultPublisher`, but we can specify it in `DefaultPublisherBuilder.`

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1938) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
Maybe it wasn't used in the past, but it is now. Closing.
