### ISSUE TITLE
Publisher Example app has a default development team identifier, instead of `none`

### ISSUE THREAD

**Issue by JakubJankowski** [ably/ably-asset-tracking-swift#303]
In the Signing and Capabilities section, the team identifier is set to `C4YGD8Z6G2`, which people from outside Ably won’t have access to, and I don’t think it should be publicly visible. I’d set it to `none` and add a point in the Example project’s readme that explains that the users will have to set their own team ID if they want to run the app on their physical devices.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1940) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
Looks like the default team ID was removed in ef6ecb1a6ef8479b96d3f0c418e5e9393078400a. But I agree we should still document how to configure the team ID. I've created #488 and will close this one.
