### ISSUE TITLE
Publisher Example App suggests to create destination coordinates of a wrong type

### ISSUE THREAD

**Issue by JakubJankowski** [ably/ably-asset-tracking-swift#307]
In the publisher example app code, in the `MapViewModel.swift` a comment says to uncomment  the  //destination = CLLocationCoordinate2D(latitude: 0, longitude: 0)` line to set coordinates. 

However, `CLLocationCoordinate2D` is not of type `LocationCoordinate?` that is required when constructing a Trackable object, so the compiler doesn't like that: `Cannot assign value of type 'CLLocationCoordinate2D' to type 'LocationCoordinate?’`

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2496) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
#419 removes this code, and we'll proper (i.e. UI) support for specifying a destination in #391.
