### ISSUE TITLE
Logger from AAT should capture events from ably-cocoa's logHandler

### ISSUE THREAD

**Issue by JakubJankowski** [ably/ably-asset-tracking-swift#329]
Currently we're using [swift-log](https://github.com/apple/swift-log) as a logger in the AAT sdk. We're creating various hardcoded instances for it depending on the context:

* In DefaultSubscriber: `let logger: Logger = Logger(label: "com.ably.tracking.Subscriber")`
* In DefaultPublisher: `let logger: Logger = Logger(label: "com.ably.tracking.Publisher")`
* In DefaultSubscriberBuilder when creating the `DefaultAbly` instance: `logger: Logger(label: "com.ably.tracking.DefaultAbly-Subscriber")`
* In DefaultPublisherBuilder when creating the `DefaultAbly` instance: `logger: Logger(label: "com.ably.tracking.DefaultAbly-Publisher")`

To align the logging mechanism with Android sdk, those loggers shouldn't be hardcoded, they should instead be passed as optionals in the subscriber and publisher's build methods. They should also be reused in the DefaultAbly wrapper, instead of creating separate loggers for it.

We should also consider dropping the swift-log lib, and use a generic approach using an interface, similarly to how [android](https://github.com/ably/ably-asset-tracking-android/blob/main/core-sdk/src/main/java/com/ably/tracking/logging/LoggingConfigurationModels.kt) does it.

Additionally, logger should also be used to capture events from the underlying ably-cocoa sdk, using the `ARTLog` logHandler (when setting `getClientOptions` in `ConnectionConfiguration` extension).

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2570) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
We believe that @JakubJankowski is already working on this.

On Android they provided an interface `LogHandler` with a single method `logMessage(level: LogLevel, message: String, throwable: Throwable? = null)`. We could do the same, or accept an instance of `Logger` from `swift-log`.

As for customising the way in which ably-cocoa logs, my memory is that the `ARTLog` class in ably-cocoa is not very well documented and there are no instructions on how to do custom logging.
