### ISSUE TITLE
Allow to enable and disable the cycling profile in the publisher

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#335]
Once the profile is ready we should add an option to enable and disable it in the publisher builder. It should be available as a `VehicleProfile` that can either be `CAR` (the profile disabled) or `BICYCLE` (the profile enabled).

Corresponding Android issue https://github.com/ably/ably-asset-tracking-android/issues/726

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-2580) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
The default value should be `CAR`.

**Comment by ikbalkaya** [comment]
This is blocked by https://github.com/mapbox-collab/Ably-DH-Collab/issues/8
