### ISSUE TITLE
Allow to get the list of trackables added to the publisher

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#336]
It should be possible to get a list of the currently added trackables of the publisher. On Android, we've used a `Flow` that emits the trackables set whenever it changes.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2579) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
On Android, this is the `trackables` flow on `Publisher`; on Swift we'd probably use a new `PublisherDelegate` method.
