### ISSUE TITLE
When trying to add a trackable that's already added we should return a success

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#340]
On Android when you try to add a trackable that's already in the publisher, we simply return a success. However, on iOS in the same situation, we throw an exception. We should unify that behaviour and make it work the same on both platforms.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2596) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
We are going to align with Android on this one, but we think it might not be the best behaviour (you might be trying to add a trackable with the same ID but with a different destination or constraints, and a successful response would be misleading). But we'll align and then whoever picks this up should make an issue for revisiting this behaviour.
