### ISSUE TITLE
Handle a scenario where the same trackable is being added multiple times

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#341]
Since we work in a multi-threaded environment we should properly handle a scenario where the same trackable is being added at the same time from multiple places. Currently in that case each add operation would call all methods and try to connect to Ably channels etc. What should happen is the trackable adding steps should be called only once and all the other add operations should simply wait for the result of the first one.

On Android, we handle the situation with the help of the [`DuplicateTrackableGuard`](https://github.com/ably/ably-asset-tracking-android/blob/main/publishing-sdk/src/main/java/com/ably/tracking/publisher/guards/DublicateTrackableGuard.kt) that makes sure only one add operation is being executed. All other add calls will be added to a list and notified when the first operation finishes and what was the result of that operation.

**Comment by lawrence-forooghian** [comment]
Just to explain how this is different to https://github.com/ably/ably-asset-tracking-swift/issues/340. Adding a trackable is an asynchronous operation that can last several seconds. This issue relates to the behaviour if you try and add a trackable _whilst an add operation for a trackable with the same ID is still in progress_, whereas #340 is about if you try and add a trackable when one with the same ID has already completed being added.

**Comment by lawrence-forooghian** [comment]
This should be done alongside #341 as they'll probably require the creation of similar mechanisms.

**Comment by lawrence-forooghian** [comment]
I'm unassigning this from myself since I'm not actively working on it. My work-in-progress can be found at https://github.com/ably/ably-asset-tracking-swift/compare/main...341-same-trackable-being-added-multiple-times (it's based on top of #440).

**Comment by deanna-lad** [comment]
The corresponding Jira issue is https://ably.atlassian.net/browse/SDK-2595
