### ISSUE TITLE
Handle the "Connection resume failed" exception from ably-cocoa

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#347]
From time to time we might get the "Connection resume failed" exception from `ably-cocoa` due to the fact that a new connection was established. Because of that, all messages that we were trying to send using the old connection will receive the error. This should not be propagated immediately to the SDK users and it should be handled on the AAT side.

We should try to retry Ably SDK calls if a "connection resume failed" error is received. Here's how it was done on Android https://github.com/ably/ably-asset-tracking-android/pull/665.

Note: There's a known issue in the Android implementation described here https://github.com/ably/ably-asset-tracking-android/issues/744

**Comment by lawrence-forooghian** [comment]
Not yet looked at this one, due to other issues having higher priority.

**Comment by deanna-lad** [comment]
The corresponding Jira issue is https://ably.atlassian.net/browse/SDK-2599

**Comment by lawrence-forooghian** [comment]
This functionality no longer exists in Android as of https://github.com/ably/ably-asset-tracking-android/commit/6542defb68e585338f947cdbbfde64da1f84369e.
