### ISSUE TITLE
Use the Idempotent Publishing feature of the Ably SDK

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#349]
We should use the [Idempotent Publishing](https://faqs.ably.com/what-is-idempotent-publishing) feature to avoid message duplication while resending location updates. To do that we need to enable the option in the Ably SDK configuration and assign IDs for the location update messages.

[This was done on Android](https://github.com/ably/ably-asset-tracking-android/pull/379/commits/236babe26b13942d01d857e49da58c16b9bf9c26) as a part of [this PR](https://github.com/ably/ably-asset-tracking-android/pull/379)

**Comment by KacperKluka** [comment]
I'm not sure if implementing this will change anything as the `idempotent publishing` seems to only be applicable to the REST publishing. We are using realtime so I'm not sure if enabling the REST idempotent publishing will change anything for the `AblyRealtime`.

**Comment by QuintinWillison** [comment]
I guess that means that the work to be done under this issue is actually to remove [this line](https://github.com/ably/ably-asset-tracking-android/blob/b05d26ee5c198186d476ad23b2d684aa80c69d6a/common/src/main/java/com/ably/tracking/common/Ably.kt#L236), needlessly setting the `idempotentRestPublishing` client option, from the Android implementation.

**Comment by JakubJankowski** [comment]
Looked at the iOS code, we're indeed using only Realtime [here](https://github.com/ably/ably-asset-tracking-swift/blob/474295752ba275fc6340f5a50a28d295ff61737f/Sources/AblyAssetTrackingInternal/AblyWrapper/SDK/AblyCocoaSDK.swift#L125)
And api specs confirm that idempotent publishing "does not apply in Realtime publishing": [(RTL6a1)](https://docs.ably.com/client-lib-development-guide/features/#RTL6a1)

So in my opinion we can close this issue, and as Quintin mentioned above - we might want to remove the line from Android implementation @KacperKluka

**Comment by KacperKluka** [comment]
I've created [an issue](https://github.com/ably/ably-asset-tracking-android/issues/774) for it in the Android repo, thanks for checking 🙇
