### ISSUE TITLE
Check whether CoreLocationAnimator progress may be bigger than 100%

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#369]
On Android it was possible for the progress to exceed 100% which lead to runtime errors. We should check if that's also the case in this project.

Android issue for reference: https://github.com/ably/ably-asset-tracking-android/issues/751

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2649) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
I've been looking into this and doing some refactoring, as part of which I discovered #375. Parking this work until we decide what to do about #375.
