### ISSUE TITLE
Upgrade Mapbox to 2.8.0

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#373]
Mapbox 2.8.0 is almost ready (currently it's in [RC](https://github.com/mapbox/mapbox-navigation-ios/releases/tag/v2.8.0-rc.1) phase) so when it will become stable we should upgrade it.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2652) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
Done in a91ec8bd31635a9192b14670b0f88de620ff4456
