### ISSUE TITLE
Make the client ID an optional parameter if users use a token-based auth

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#384]
When users use a token-based auth we should make the client ID an optional configuration parameter.

For more details look here https://github.com/ably/ably-asset-tracking-common/issues/59

**Comment by lawrence-forooghian** [comment]
@KacperKluka I believe this is already the case for Swift; see the [`ConnectionConfiguration.init(clientId: String? = nil, authCallback: @escaping AuthCallback)`](https://github.com/ably/ably-asset-tracking-swift/blob/c382202a11a68373b1b0036feb0f17c1a944cbb0/Sources/AblyAssetTrackingCore/Configuration/ConnectionConfiguration.swift#L52-L56) initializer, which takes an optional client ID.

I notice that in https://github.com/ably/ably-asset-tracking-android/pull/768 you've actually not only made the client ID optional when using token-based auth, but actually _deprecated_ the ability to pass a client ID when using token-based auth. I was wondering what was the motivation for this? It's valid to pass a client ID to the Ably SDKs even when using token-based auth, for example to set a specific client ID if the token specifies a wildcard ID (see [`RSA15b`](https://sdk.ably.com/builds/ably/specification/main/features/#RSA15b)). Should we not preserve the ability to do this in Asset Tracking too?

**Comment by KacperKluka** [comment]
> Should we not preserve the ability to do this in Asset Tracking too?

We've discussed it and decided that even though it's possible to provide a client ID with a token-based auth it is not meant to be used in the AAT scope. While designing the AAT API we are on purpose narrowing the options to only those that make the most sense. So even though you can provide a wildcard client ID in the token, there's virtually no use-case for it in the AAT world 🤔

**Comment by lawrence-forooghian** [comment]
Alrighty, should I remove the `clientId` parameter from the initializer in Swift then too?

**Comment by lawrence-forooghian** [comment]
Sorry, by "remove" I meant deprecate, like in Android.

**Comment by lawrence-forooghian** [comment]
Cool, will do 🙂
