### ISSUE TITLE
Add "Navigation Settings" section to the publisher example app settings

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#387]
In the Android example app, we have a "Navigation Settings" section at the top which allows you to configure settings related to the navigation engine. Those settings are:

* Location source (Phone, <del>Ably channel</del>, S3) - split to #410 and #411
* <del>Simulation channel name (for Ably channel location source)</del> – We won't do this on iOS
* S3 file (for S3 location source)
* <del>Routing profile</del> - split to #409
* <del>Vehicle profile</del> - split to #408

<del>It might be that on iOS the `Ably channel` location source is not available and in this case, we won't be adding it to the settings screen.</del> – That's correct, it doesn't exist

The S3 location source is meant for replaying the already recorded trip data from a file from an S3 bucket. The app should retrieve the list of available files and show them in a drop-down list in the `S3 file` preference. Probably we need to fix https://github.com/ably/ably-asset-tracking-swift/issues/290 before doing this.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2689) by [Unito](https://www.unito.io)

**Comment by arturjaworski** [comment]
Attaching Android example screenshots
![Screenshot_20221005_134321](https://user-images.githubusercontent.com/1076431/194249367-7944be57-66be-4a3f-85c9-2df07474798e.png)
![Screenshot_20221005_134331](https://user-images.githubusercontent.com/1076431/194249383-7aeff733-61f1-413c-9f2a-a1ff03d48a63.png)
![Screenshot_20221005_134341](https://user-images.githubusercontent.com/1076431/194249393-b72d15d1-3547-41a8-b40b-996c276c691c.png)

**Comment by lawrence-forooghian** [comment]
The Ably channel location source is not available on iOS. I'm going to update the description of the issue to reflect this.

**Comment by lawrence-forooghian** [comment]
I've split this out into separate issues (see updated description of this issue), so am closing this one.
