### ISSUE TITLE
Make sure the publisher example app keeps tracking and sending locations when the app is in the background

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#388]
The publisher should keep working when the app goes to the background or the phone screen is turned off. In the real world, the users will be using the publisher SDK for long periods of time and we can't expect that the SDK will always be used in the foreground the whole time.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2690) by [Unito](https://www.unito.io)

**Comment by arturjaworski** [comment]
Hello, I've tested it, and it looks like it works properly. The longest background session I've made lasted about 5 hours.
