### ISSUE TITLE
Allow to set a destination when adding a trackable in the publisher example app

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#391]
When adding a trackable we should be able to set its destination. On Android, we show a map with a pin (map marker) in the middle and the user can move the map around to use the location under the pin as the asset destination.

Connected to https://github.com/ably/ably-asset-tracking-swift/issues/389

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2693) by [Unito](https://www.unito.io)

**Comment by arturjaworski** [comment]
Attaching Android example app screenshots

<img src="https://user-images.githubusercontent.com/1076431/194254136-c5ad3b46-103d-4da9-b041-5ca134a11972.png" width="50%">
<img src="https://user-images.githubusercontent.com/1076431/194254257-4e8ab58e-2568-4a2f-9c76-e5d65bdf8461.png" width="50%">
<img src="https://user-images.githubusercontent.com/1076431/194254299-7776931b-92fe-45f2-840e-7b1806bb0767.png" width="50%">
<img src="https://user-images.githubusercontent.com/1076431/194254336-fa2a5b63-c90e-4643-a2e1-72bba68565f0.png" width="50%">

**Comment by lawrence-forooghian** [comment]
I think that this is just adding a field to the "add trackable" screen that we’ll add in #389, perhaps with an extra screen for populating this field's value using a map.
