### ISSUE TITLE
Show the raw location in the subscriber example app

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#393]
We can receive both enhanced and raw locations from the publisher SDK. Currently, the subscriber example app only displays the enhanced ones. We should add a second map marker that will show the raw locations on the map, if they are being received. On Android, the raw map marker icon is the same as the enhanced one, but its alpha (transparency) is lower and the marker color is red.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2695) by [Unito](https://www.unito.io)

**Comment by arturjaworski** [comment]
Attaching Android example app screenshots

<img src="https://user-images.githubusercontent.com/1076431/194267579-e1002be9-e02a-4fd6-985a-67fa52feedc9.png" width="50%">
