### ISSUE TITLE
Show the accuracy circle in the subscriber example app

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#394]
We receive the accuracy value for each location and we should display it on the map. On Android, we show it as a circle with its radius equal to the accuracy value and its center placed at the center of the map marker icon. The accuracy circle should be visible for both enhanced and raw locations markers.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2696) by [Unito](https://www.unito.io)

**Comment by arturjaworski** [comment]
Attaching Android example app screenshots

<img src="https://user-images.githubusercontent.com/1076431/194267579-e1002be9-e02a-4fd6-985a-67fa52feedc9.png" width="50%">

**Comment by arturjaworski** [comment]
<img src="https://user-images.githubusercontent.com/1076431/194310969-da0aab87-35b8-46de-9d20-1c03c13fc00d.jpeg" width="50%">

The accuracy circle is already implemented.

**Comment by arturjaworski** [comment]
Closing as discussed with @KacperKluka
