### ISSUE TITLE
When using token-based auth, we can only publish presence messages if the user passes a client ID to `ConnectionConfiguration`

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-asset-tracking-swift#401]
If we pass a `nil` client ID to [`ConnectionConfiguration.init(clientId: String? = nil, authCallback: @escaping AuthCallback)`](https://github.com/ably/ably-asset-tracking-swift/blob/80d2962eecdb9431aca766707a85da52c25aba09/Sources/AblyAssetTrackingCore/Configuration/ConnectionConfiguration.swift#L52-L56), then any functionality that requires AAT to publish a presence message will fail with the error `attempted to publish presence message without clientId`.

This error is emitted by ably-cocoa [here](https://github.com/ably/ably-cocoa/blob/d5741ce8d3bbce0cfda7e91ff5dccc3004f81eb0/Source/ARTRealtimePresence.m#L503).

I believe that we need to fix https://github.com/ably/ably-cocoa/issues/1126 to fix this issue. There is already [a comment](https://github.com/ably/ably-asset-tracking-swift/blob/80d2962eecdb9431aca766707a85da52c25aba09/Sources/AblyAssetTrackingCore/Configuration/ConnectionConfiguration.swift#L43) in AAT alluding to this, but no corresponding AAT issue, and the comment is misleading as suggests that AAT currently doesn't allow you to pass a `nil` client ID – it does, it just doesn't behave correctly if you do so.

For concrete examples of this issue, see the test failures introduced in https://github.com/ably/ably-asset-tracking-swift/commit/f2b310ae56c7eb63bfca7338820a23c9bd1c4437.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2701) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
"The ability to specify a client ID when using token-based authentication has been deprecated." https://github.com/ably/ably-asset-tracking-swift/blob/f2b310ae56c7eb63bfca7338820a23c9bd1c4437/Sources/AblyAssetTrackingCore/Configuration/ConnectionConfiguration.swift#L53

**Comment by maratal** [comment]
That's because `publishPresence:` is called before the callback of the `_requestToken:` [here](https://github.com/ably/ably-cocoa/blob/d5741ce8d3bbce0cfda7e91ff5dccc3004f81eb0/Source/ARTAuth.m#L599) So, I guess all presence messages should be queued until `ably-cocoa` properly authorize itself.

**Comment by lawrence-forooghian** [comment]
Does the feature spec have anything to say about this? It sounds like a behaviour we'd only want to implement if it was specified.

**Comment by lawrence-forooghian** [comment]
Hey @maratal. I noticed that there was a difference between how ably-cocoa and ably-java are implementing RTP8f of the Ably feature spec, so I opened https://github.com/ably/specification/pull/106 to address this. I believe that if we implement the behaviour mentioned there in ably-cocoa then, as long as ably-cocoa also implements [RTP16b](https://sdk.ably.com/builds/ably/specification/main/features/#RTP16b), this asset tracking issue should not occur. What do you think?

**Comment by maratal** [comment]
Looks like it was implemented ages ago https://github.com/ably/ably-cocoa/pull/317 but something is broken there, will dive into it.

**Comment by maratal** [comment]
@lawrence-forooghian well, that works =) https://github.com/ably/ably-cocoa/pull/1515

**Comment by lawrence-forooghian** [comment]
Hi @maratal - I've added a question for you: https://github.com/ably/ably-cocoa/pull/1515#issuecomment-1289336072
