### ISSUE TITLE
Fix lint errors for podspec

### ISSUE THREAD

**Issue by mmiedlarz** [ably/ably-asset-tracking-swift#41]
Calling `pod spec lint` will produce several build errors related to the `MapboxCoreNavigation` library, which are related to [this issue](https://github.com/mapbox/mapbox-navigation-ios/issues/2674). 

We can still install SDKs using CocoaPods with a direct git path to podspec, but we won't be able to deploy it to CocoaPods later.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-746) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
We don’t support CocoaPods for this project. IMO this task should be closed @jamienewcomb @AndyNicks

**Comment by AndyNicks** [comment]
@lukasz-szyszkowski agree.

**Comment by AndyNicks** [comment]
CocoaPods is not supported in this project
