### ISSUE TITLE
Upload location history data to S3 after it's emitted by the SDK in the publisher example app

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-asset-tracking-swift#413]
h2. Description
In the Android publisher example app, if the app has been given an S3 configuration, then whenever the asset tracking SDK emits a {{locationHistory}} callback (i.e. when it says that some trip location recorded data is available) [then the app will upload this data to S3|https://github.com/ably/ably-asset-tracking-android/blob/8a9d6b99b45d3a41d333ff0d60337ee79f40c4a8/publishing-example-app/src/main/java/com/ably/tracking/example/publisher/PublisherService.kt#L86-L90].

We want the iOS app to do the same thing.

h2. Depends on
* #410 - we need the ability to provide the publisher app with an S3 config
* #414 - we need the ability to use our S3 client to upload {{LocationHistoryData}} objects to S3
* #111 - we need the {{locationHistory}} callback to be implemented in the publisher

**Comment by deanna-lad** [comment]
The corresponding Jira issue is https://ably.atlassian.net/browse/SDK-2714

**Comment by lawrence-forooghian** [comment]
This is blocked by #111, which is awaiting a response from Mapbox.

**Comment by lawrence-forooghian** [comment]
This is no longer blocked.
