### ISSUE TITLE
Allow copy/paste on Uploads view

### ISSUE THREAD

**Issue by mikelee638** [ably/ably-asset-tracking-swift#482]
As an AAT iOS tester, I want to be able to copy and paste the upload file names in Settings > Uploads in the publisher example app so that when providing feedback, I don't have to type out the file names.

**Comment by lawrence-forooghian** [comment]
@mikelee638 just to mention, the implemented solution only works on iOS 15 and above. If this turns out to be a problem we can come up with something else.
