### ISSUE TITLE
Rework the sdk to use workers and worker queue to handle events

### ISSUE THREAD

**Issue by JakubJankowski** [ably/ably-asset-tracking-swift#523]
The approach should be aligned to the way it's handled on the [Android sdk](https://github.com/ably/ably-asset-tracking-android/blob/main/common/src/main/java/com/ably/tracking/common/workerqueue/WorkerQueue.kt).

More details will be added later.

**Comment by lawrence-forooghian** [comment]
What's the scope of this issue, @JakubJankowski? Are you reproducing the worker mechanism and all the workers exactly as they exist in Android? (If so, that sounds like a lot of work for one issue.) Or is just to introduce the mechanism and then slowly bring the individual workers in line with Android?

**Comment by lawrence-forooghian** [comment]
It would be good, as a first piece of work, to maybe do a PR that just introduces the worker queue and related protocols and tests?

**Comment by JakubJankowski** [comment]
Hey @lawrence-forooghian - my plan is to introduce the WorkerQueue and rework the current implementation of the subscriber sdk. The scope is indeed quite large.

I think it's indeed a good idea to set up the WorkerQueue and related interfaces as a separate PR first, to make sure we're all on the same page on how it should be implemented on iOS, so I'll extract this part from my current work, finish it up and I'll submit a PR for it.

**Comment by lawrence-forooghian** [comment]
> I think it's indeed a good idea to set up the WorkerQueue and related interfaces as a separate PR first, to make sure we're all on the same page on how it should be implemented on iOS, so I'll extract this part from my current work, finish it up and I'll submit a PR for it.

Sounds good, thanks!
