### ISSUE TITLE
The publisher should close the Ably connection when it has no trackables

### ISSUE THREAD

**Issue by JakubJankowski** [ably/ably-asset-tracking-swift#528]
By default we start the connection with ably, even If there are no trackables in a Publisher, since the `ARTClientOptions.autoConnect` in Ably Cocoa defaults to `true`.

We should change this behaviour:

* The connection should be stopped when the publisher is created -we need to pass `false` to the `ARTClientOptions.autoConnect`
* When the first trackable is added the connection should be started
* When the last trackable is removed the connection should be stopped

Here's a related Android [issue](https://github.com/ably/ably-asset-tracking-android/issues/170), with some more info/discussions/considerations.

**Comment by AndyTWF** [comment]
Added this to the 1.0.0 milestone - as this is behaviour that happens in Android

**Comment by lawrence-forooghian** [comment]
@AndyTWF I believe this will be covered by #563 (for starting the connection) and #557 and #559 (for stopping the connection) — no additional work required, right?

**Comment by lawrence-forooghian** [comment]
Actually, the other change is to not auto connect. Would that be something we'd want to add once these workers are all implemented?

**Comment by AndyTWF** [comment]
Have moved no autoconnecting into https://github.com/ably/ably-asset-tracking-swift/issues/589 as part of the 1.0.0 milestone
