### ISSUE TITLE
Wait for Ably connection to leave the "suspended" state before performing operations on Ably

### ISSUE THREAD

**Issue by JakubJankowski** [ably/ably-asset-tracking-swift#533]
When the Ably connection (or a channel) state is suspended, then no Ably operations will succeed. Therefore, there is no point in trying to perform any operation on Ably until the state changes to something else (like connected).

More details, discussions etc. in related Android sdk's issue [#973](https://github.com/ably/ably-asset-tracking-android/issues/973)

I'd suggest this should be worked on after the Worker Queue rework is completed in #523.

**Comment by AndyTWF** [comment]
Going to close this as covered in 1.0.0 milestone work here: https://github.com/ably/ably-asset-tracking-swift/issues/565
