### ISSUE TITLE
Make publisher.track() and publisher.add() return instantly

### ISSUE THREAD

**Issue by JakubJankowski** [ably/ably-asset-tracking-swift#534]
At the moment, if connections to ably are slow, they block publisher.track() and publisher.add(), preventing control from returning to the caller.

To fix this, we should add the trackable to the publisher immediately and return control to the caller - allowing the ably connection startup to happen in the background.

More info in related Android sdk issue [#966](https://github.com/ably/ably-asset-tracking-android/issues/966)

**Comment by AndyTWF** [comment]
Closing as covered by https://github.com/ably/ably-asset-tracking-swift/issues/563, https://github.com/ably/ably-asset-tracking-swift/issues/558 and https://github.com/ably/ably-asset-tracking-swift/issues/554
