### ISSUE TITLE
Subscriber Worker Queue: Update Publisher Presence

### ISSUE THREAD

**Issue by AndyTWF** [ably/ably-asset-tracking-swift#592]
Implement the following worker for then subscriber:

* UpdatePublisherPresence

This worker takes a list of presence update messages and sends them to the subscriber for processing (very much how we currently do `performPresenceUpdated`) and also triggers a trackable state update.

As part of this, we probably want to make AAT Swift behave the same as `emitStateEventsIfRequired` in Android - which takes into account channel/connection state and also does things around trackable state and resolutions.

**Comment by lawrence-forooghian** [comment]
PR #639 resolves this, but it's currently blocked awaiting PR #617.
