### ISSUE TITLE
Unify the way of parsing enums sent over Ably channels across all platforms

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-asset-tracking-swift#99]
We need to unify the way of parsing enums because now it's different on each platform. We've agreed to send enum values as strings written in `SCREAMING_CAMEL_CASE`. For example, if the enum has the value `HighAccuracy` it sent as `HIGH_ACCURACY`.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-747) by [Unito](https://www.unito.io)

**Comment by lukasz-szyszkowski** [comment]
I've checked this and all send enum values are the same on both platforms hence I'm closing this issue.
